### ISSUE TITLE
✨ 11/18 데드라인까지 TODO 리스트 

### ISSUE THREAD

**Issue by wody-d** [DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS#164]
## 📝 Todo
- [x] 로그인 UI 수정
- [x] 비밀번호 변경
- [x] 닉네임 수정
- [x] 이용약관, 개인정보방침 처리 
- [x] 카카오로그인 취소했을 때 로딩뷰 안없어지는 버그 수정 
- [x] 행성 초대 UI 수정
- [x] 행성 초대
