### ISSUE TITLE
♻️프로필 탭 수정

### ISSUE THREAD

**Issue by LentoAssai** [DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS#183]
## 💬 Description
프로필 탭을 수정합니다.

## 📝 Todo
- [x] 행성 상태 분기처리 제거
- [x] 활동 내역 Binding (내가 방문한 장소들 개수 받아와야함)
- [x] 서비스 추가 및 연결
- [x] 디데이 수정 UI 구현
- [x] 행성 나가기 API 통신
