### ISSUE TITLE
♻️배포 후 UI 수정

### ISSUE THREAD

**Issue by LentoAssai** [DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS#231]
## 💬 Description
배포 후 발표 전까지 필요한 UI들을 수정합니다.

## 📝 Todo
- [x] 프로필 탭에서 공지사항 지우기
- [x] 1대1 문의 추가하기
- [x] 로그 탭에서 별자리 gyro 적용
- [x] 런치스크린 추가
- [x] 탭바 수정
- [x] 행성 나가기 페이지에서 뒤로가기 시 탭바 사라지는 이슈 해결
