### ISSUE TITLE
♻️코스관련 API 호출 관련 리펙터

### ISSUE THREAD

**Issue by LentoAssai** [DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS#232]
## 💬 Description
코스관련 API를 호출할 때 관련하여 보완할 점들을 리펙터합니다.

## 📝 Todo
- [x] API 호출 중에는 progress 처리하기
- [x] 후기 등록 시 이미지 용량 처리하기 (한 이미지당 최대 5MB, 한 후기당 최대 50MB)
- [x] 후기 등록화면에서 뒤로가기 예외 처리하기
