### ISSUE TITLE
✨ 배포후 TODO List

### ISSUE THREAD

**Issue by luminouxx** [DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS#233]
## 💬 Description
오늘 회의를 한 후 수정해야 할 것들을 TODO List로 정리해 보았습니다.

## 📝 Todo
- [ ] 1. 지도 버튼 크기 맞추기
- [ ] 2. MyConstellationView Gesture recognizer 추가
- [ ] 3. 사진 클릭시 확대
- [ ] 4. 무한 스크롤 구현
- [ ] 5. 사진 없을 때, 화면 만들기
- [ ] 6. API 호출시 인디케이터 넣기
