### ISSUE TITLE
🚑심사 Reject 해결

### ISSUE THREAD

**Issue by LentoAssai** [DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS#238]
### Guideline 1.5 - Safety - Developer Information

The support URL specified in your app’s metadata, https://www.notion.so/Help-1bfcca8f004949b290c526219907d89a, does not properly navigate to the intended destination.

The URL still does not include your contact information.

<br>

### Guideline 2.1 - Performance - App Completeness

We discovered one or more bugs in your app. Specifically, your app failed to produce any further action when we successfully went into the app using the invite code on another device.

<br>

### Guideline 5.1.1 - Legal - Privacy - Data Collection and Storage

Your app still doesn’t sufficiently explain the use of the location in the purpose string. The permission request alerts need to explain and include an example of how your app will use the requested information.

## 📝 Todo
- [x] 지원 URL 수정
- [x] 초대코드 입력 시 메인화면으로 전환
- [x] Info.plist 수정
- [x] 리뷰 작성 화면에서 코스 삭제하는 코드 수정
