### ISSUE TITLE
♻️QA 수정사항 반영

### ISSUE THREAD

**Issue by LentoAssai** [DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS#247]
## 💬 Description
1차 QA로 수정사항들을 반영합니다.

## 📝 Todo
- [x] 별자리 Gyro의 limit을 제한합니다.
- [x] 리뷰 등록 시 사진 crop 기능을 제거합니다.
- [x] 마이페이지에서 별자리 후기와 좋아하는 코스를 수정합니다.
- [x] 리뷰 등록 및 수정 시 사진의 순서를 바꿀 수 있게 합니다.
