### ISSUE TITLE
♻️QA 1차적용

### ISSUE THREAD

**Issue by kimscastle** [DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS#249]
## 💬 Description
2022년 12월 6일에 진행했던 내부 QA 적용 issue입니다

## 📝 Todo
- [x] HomeViewController에서 기존에 데이트 dday라벨 자리를 비워놨었는데 없애기로 해서 적용
- [x] profileview에서 iphone mini에서 글씨가 잘리는 부분 수정
- [x] homeviewcontroller에서 캘린더 중복 선택되는 부분 수정
