### ISSUE TITLE
♻️  QA 수정사항 List

### ISSUE THREAD

**Issue by luminouxx** [DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS#252]
## 💬 Description
- QA 수정사항을 반영합니다.

## 📝 Todo
- [ ] 티켓 전체 gmarketsans 폰트 변경
- [ ] 좋아요 기능 삭제 
- [ ] 수정 버튼 추가
- [ ] 인디게이터 색상 변경
- [ ] 뒤집기 버튼 크게
