### ISSUE TITLE
✨Xcode 템플릿 추가

### ISSUE THREAD

**Issue by LentoAssai** [DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS#3]
## 💬 Description
Xcode 템플릿을 추가합니다.

## 📝 Todo
- [x] ViewController 템플릿 추가
- [x] ViewModel 템플릿 추가
- [x] shell script 추가
