### ISSUE TITLE
♻️디자인 변경에 따른 컴포넌트 수정 (NavigationBar, SmallRectButton)

### ISSUE THREAD

**Issue by LentoAssai** [DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS#58]
## 💬 Description
#38 코스 등록 과정에서 필요한 NavigationBar를 구현했다가, 디자인이 변경되어 수정된 디자인으로 다시 구현합니다.

## 📝 Todo
- [x] 지도가 보여지는 화면의 Nav-bar 구현
- [x] 장소 검색 화면의 Nav-bar 구현
- [x] 코스 디테일 작성 화면의 Nav-bar 구현

### 1번 작업
<p>
<img width="250" alt="스크린샷 2022-10-20 22 54 41" src="https://user-images.githubusercontent.com/88371913/196968278-2a7b20a7-370d-409e-95f2-79bb5e9522be.png">
</p>
- 텍스트필드 클릭 시 push로 이동

### 2번 작업
<p>
<img width="250" alt="스크린샷 2022-10-20 22 54 56" src="https://user-images.githubusercontent.com/88371913/196968341-27b9d900-accc-4291-a309-b04c3932dc52.png">

<img width="250" alt="스크린샷 2022-10-20 22 55 22" src="https://user-images.githubusercontent.com/88371913/196968492-61d4046d-a7d3-4c8b-b399-15e4840c9b43.png">
</p>

- 코스 추가가 하나도 안되어있다면 완료버튼 비활성화
- 코스 추가 버튼을 누르면 취소 버튼으로 토글
- 통신은 텍스트를 입력할 때마다 (`debounce` 사용 고려하기)
### 3번 작업
- 일정 선택을 해서 날짜가 들어갈 때 Animation 추가하기
